apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: ghcr.io/xcyrodilx/bank-api:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9090
            initialDelaySeconds: 40
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bank-api
  namespace: bank
spec:
  selector:
    app: bank-api
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
