apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-web
  namespace: bank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-web
  template:
    metadata:
      labels:
        app: bank-web
    spec:
      containers:
        - name: bank-web
          image: ghcr.io/xcyrodilx/bank-web:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: bank-web
  namespace: bank
spec:
  selector:
    app: bank-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
